#!/bin/sh

# Set these paths appropriately

BIN="/Users/clemencebarsi/Downloads/bin"
CMD="/Users/clemencebarsi/Downloads/cmd"
LIB="/Users/clemencebarsi/Downloads/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/ancient-greek.par

$TOKENIZER $* |
# tagging
$TAGGER $OPTIONS $PARFILE

