#!/bin/sh

# Set these paths appropriately

BIN="/Users/clemencebarsi/Downloads/bin"
CMD="/Users/clemencebarsi/Downloads/cmd"
LIB="/Users/clemencebarsi/Downloads/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/old-french-abbreviations
PARFILE=${LIB}/old-french.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
