#!/bin/sh

# Set these paths appropriately

BIN="/Users/clemencebarsi/Downloads/bin"
CMD="/Users/clemencebarsi/Downloads/cmd"
LIB="/Users/clemencebarsi/Downloads/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/persian-coarse.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
